Feature/controllers
alekseyknows/FilmsAboutBack pull request #20
Opened 2021-07-23 14:40 UTC by DimetilTriptAmin

2021-07-23 14:49 UTC, alekseyknows requested changes
fix return type in getRating method to int

2021-07-23 14:52 UTC, alekseyknows approved these changes

2021-07-23 15:38 UTC, unitondev requested changes
remake

2021-07-26 10:53 UTC, alekseyknows approved these changes

2021-07-26 11:06 UTC, unitondev approved these changes

2021-07-26 12:14 UTC, merged